#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR/haar_knn/
python3 "$DIR/haar_knn/main.py"

cd $DIR/ImageResizer/
# /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -jar "$dirname/ImageResizer/out/artifacts/ImageResizer_jar/ImageResizer.jar"
# /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -jar "$DIR/ImageResizer/out/artifacts/ImageResizer_jar/ImageResizer.jar"
java -Dfile.encoding=UTF-8 -jar "$DIR/ImageResizer/out/artifacts/ImageResizer_jar/ImageResizer.jar"
