#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

Images="$DIR/Images/"

for file in "$Images"*;
do 
	echo "line 1"
   	echo $file
   	echo "line 2"
	echo $DIR/In/
	echo "line 3"
	cp $file $DIR/In/original.jpg
	ls $DIR/In/
	echo "line 4"
	sh $DIR/compress
	wait
	echo "line 6"
	
done

# for entry in "$DIR/Images"/;
# do
#   echo "$entry"
# done