#!/bin/bash

cd ~/Programming/Facial\ Haac/haar_knn/
/usr/local/bin/python3.7 "/Users/roshan/Programming/Facial HAAC/haar_knn/main.py"

cd ~/Programming/Facial\ Haac/ImageResizer/
/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -jar "/Users/roshan/Programming/Facial HAAC/ImageResizer/out/artifacts/ImageResizer_jar/ImageResizer.jar"

